author: "Carl Colmant"
baseurl: ""           # falls Unterpfad, sonst leer lassen
title: "Gesichtserkennung"
markdown: kramdown
theme: minima           # oder ein anderes Jekyll-Theme

include:
  - "Vortrag_Projeckt/inference_results"
exclude:
  - ".gitignore"
  - "node_modules/"